### ISSUE TITLE
Update ember-resolver addon to use `resolveEngine`.

### ISSUE THREAD

**Issue by rwjblue** [dgeb/ember-engines#10]
For now, apps that consumes engines must use the `ember-engines/resolver` module instead of `ember/resolver` or `ember-resolver`. Once we are confident in the `resolveEngine` implementation added in #9 we should push those changes upstream into ember-resolver (possibly after publishing a beta version of this addon).  Then we can remove `addon/resolver.js`.

**Comment by asakusuma** [comment]
@rwjblue are we confident in `resolveEngine` now? If so I will take a crack at this.

**Comment by rwjblue** [comment]
:shipi
