### ISSUE TITLE
this.mount loading/error substates generation.

### ISSUE THREAD

**Issue by nathanhammond** [dgeb/ember-engines#103]
We need the behavior of creating `loading`/`error` substates as peers to the engine when using `this.mount` inside of an application's `router.js`. The end result will be similar to the implementation here:
https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/dsl.js#L44-L47

/cc @knownasilya

**Comment by knownasilya** [comment]
Will try to look at this this week. Thanks for the link!

**Comment by trentmwillis** [comment]
@knownasilya have you had any chance to look into this? If not, would you mind if I picked it up?

**Comment by knownasilya** [comment]
Go ahead, I'm swamped:)

**Comment by trentmwillis** [comment]
Will take care of it then

**Comment by mydea** [comment]
Should this already work? In my app, using ember@2.8.0 & ember-engines@0.3.0, loading & error substates do not seem to work for a routeable engine.

**Comment by nathanhammond** [comment]
@mydea Can you open a failing test case against this repo as a new issue?

**Comment by trentmwillis** [comment]
@mydea to answer your question, it _should_ work, but substates seem to be rather finicky so it could very well be something was missed.

**Comment by andreamancuso** [comment]
@mydea Sorry to trouble you, did you manage to get the loading sub-states working on your engines? I tried several combinations to no avail

**Comment by mydea** [comment]
Sadly, no - see https://github.com/dgeb/ember-engines/issues/193

**Comment by nathanhammond** [comment]
@mydea @andreamancuso We've reduced it to a simple reproduction, it's all set for one of you to dive in and solve it! 😜 (Yes, this is the "PRs accepted" response, but it's not something we're presently trying to solve for at LI and so it's not on the to-do list yet.)

**Comment by knownasilya** [comment]
@nathanhammond where is this reproduction?

**Comment by nathanhammond** [comment]
@knownasilya https://github.com/dgeb/ember-engines/issues/193#issuecomment-246450033
