### ISSUE TITLE
input helper not sending enter/action event to controller

### ISSUE THREAD

**Issue by venuswei** [dgeb/ember-engines#115]
Using in-repo addon right now and trying to execute a simple form that sends an action to a controller upon 'enter'. 

The action/enter event from the input helper is not sending to the controller. 

`{{input type='text' value=chatMessage action="postMessage"}}`

`{{input type='text' value=chatMessage enter="postMessage"}}`

Anyone else face this issue?

**Comment by venuswei** [comment]
Any updates on this?

**Comment by dgeb** [comment]
@venuswei a failing test or example repo would help us investigate

**Comment by dgeb** [comment]
Closing for lack of a test or example repo. Please reopen if you continue to have this problem.
