### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by forgetboy** [dgeb/ember-engines#119]
Sorry to have to create an issue for this - couldn't find a better way to request a release. Some of the changes in master contain fixes to allow mounting of an engine within an engine, which, I am looking to use -

https://github.com/dgeb/ember-engines/compare/v0.2.3...master

Would greatly appreciate this. Thanks.

**Comment by dgeb** [comment]
Just released v0.2.4 :shipit:

**Comment by forgetboy** [comment]
Thank you!
