### ISSUE TITLE
Setting resolver during tests

### ISSUE THREAD

**Issue by trentmwillis** [dgeb/ember-engines#123]
One pain point we've found while working with in-repo-engines is that integration/unit tests can be frustrating to get working properly. A large part of this is due to the resolver used by tests being set once globally and usually only reflects the resolver used by the host application and not the engine itself.

Since there are obviously scenarios where we would want to integration/unit test a component (or something else) within an in-repo-engine, it might make sense to build in a way to easily set the Engine associated with a specific test module. Something like:

```js
import { test, moduleForComponent } from 'ember-qunit';

moduleForComponent('x-foo', {
  integration: true,
  engine: 'my-engine'
});
```

Which will grab the `resolver` and `modulePrefix` after looking up the Engine and use those for the resolver for the current test module.

Note: I believe we could work in support for this from this addon, but it would likely be better situated somewhere in `ember-test-helpers`.

**Comment by mydea** [comment]
Has there been any progress on this? We'd love to use integration tests for our in-repo engine's components.

**Comment by trentmwillis** [comment]
This is now possible by setting a custom resolver per-module in `ember-test-helpers@^0.5.33`
