### ISSUE TITLE
Allow custom config path in package.json using configPath

### ISSUE THREAD

**Issue by cklimkowsky** [dgeb/ember-engines#133]
Instead of a "config" folder, our engine has "ember-config" as the config directory.

In package.json, we have this specified:
```
"ember-addon": {
  "configPath": "ember-config"
},
```

However, this value is ignored. My `config` object is returned as empty. When I rename "ember-config" to "config", my `config` object is resolved correctly.

**Comment by trentmwillis** [comment]
@cklimkowsky I think an update needs to occur [at this line](https://github.com/dgeb/ember-engines/blob/v0.2/lib/engine-addon.js#L46) if you want to take a crack at a PR to support this. Could probably do something similar to [what is done in Ember-CLI](https://github.com/ember-cli/ember-cli/blob/084e9ea1db867c7a120d54cf9ebbe06989934b0f/lib/models/project.js#L179-L187), or maybe even wholesale use that method.
