### ISSUE TITLE
Is there any way to mount an app as an engine?

### ISSUE THREAD

**Issue by dfalling** [dgeb/ember-engines#136]
I've fumbled around a while trying to get this to work.  Is there a way to mount an entire Ember application as an engine inside another application?  My attempts at this so far have failed because of infinite loops caused by app/* files exporting themselves (since the app doesn't know to look in `addons/*`).  Thanks!

**Comment by dgeb** [comment]
Applications can't be mounted directly inside other applications. An application must be restructured as a routable or routeless engine, as described in the README, before it can be mounted inside another application.

**Comment by dfalling** [comment]
Ok, thanks for the info!
