### ISSUE TITLE
In in-repo-engines: Support access to parent project components

### ISSUE THREAD

**Issue by boehlke** [dgeb/ember-engines#139]
I tried to use in-repo-engines for lightweight modularization of my growing ember app. The problem I encountered was, that my in-repo-engines don't see components from the main app. Unfortunately, the "dependencies" mechanism in the in-repo-engine's package.json doesn't work properly.

Would it be possible to optionally have an in-repo-engine inherit all components from the main app, including transitively included components (from other addons)? My in-repo-engines are heavily coupled to the main project anyway.

**Comment by dgeb** [comment]
You'll need to separate components that you wish to share into an addon and then make that addon a dependency of both your application and engine. The shared addon and the engine could both be in-repo.
