### ISSUE TITLE
Accessing parent route params, where the parent route is part of the consuming Application

### ISSUE THREAD

**Issue by nucleartide** [dgeb/ember-engines#140]
Hello! Just had a question about parent routes. Let's say I have the following route structure:

```js
// inside app/router.js
Router.map(function() {
  this.route('user', { path: '/:username' }, function() {
    this.mount('blog')
  })
})

// inside "blog" engine's route map
buildRoutes(function() {
  this.route('posts')
})
```

Inside the `posts` route in the `blog` engine, I want to call `const { username } = this.paramsFor('user')` to get the username, but this doesn't work. Is there a way to access parent route params across the parent/engine boundary? It's pretty easy to just write an ad-hoc function to parse `window.location.pathname`, but that seems kinda hacky.

**Comment by trentmwillis** [comment]
In general, Engine's shouldn't have knowledge of their host application's structure. You should think of it this way: _Engine's should know what **they need**, not what their **parent has**_.

The **TL;DR** of below is: Send the `username` as part of a Service dependency.

The long explanation is: in the above example, by calling `this.paramsFor('user')` your Engine is saying, "I know my parent has a `user` route, so I'm going to get it". Instead, your Engine should be saying something like "I need to know this user's `username`, so my parent should provide that."

In the Engine, you can do this by specifying a dependency on a Service that tracks the current user's info:

```js
const Eng = Engine.extend({
  dependencies: {
    services: [
      'currentUserInfo'
    ]
  }
});
```

Your post route can then just use that service:

```js
Route.extend({
  currentUserInfo: inject.service(),
  model() {
    const username = this.get('currentUserInfo.username');
    // do stuff with username
  }
});
```

Note: we do a very similar thing in our application where we have a service that tracks the currently authenticated user's information.

Hope that helps!

**Comment by nucleartide** [comment]
Ahh that makes sense...thanks for the heads up! I'm not using ember-engines at the moment (at work we decided the "multiple tools in one package" approach wasn't appropriate) but I'll keep this in mind in the future.
