### ISSUE TITLE
Default `configPath` for addons points to dummy app's config path.

### ISSUE THREAD

**Issue by dgeb** [dgeb/ember-engines#149]
As per #133, we now allow a custom `configPath` to be set in an engine's `package.json`. If `ember-addon/configPath` is set, then this value will be used instead of the default path of `config`.

Unfortunately, `ember-addon/configPath` _is_ set by default in new addon projects, and the default value is `"tests/dummy/config"`. New engines are now using this the environment settings from the dummy app (`tests/dummy/config/environment.js`) instead of `config/environment.js`.

@rwjblue any idea how to best untangle this while still allowing, but not requiring, custom config paths?

**Comment by dgeb** [comment]
Some options:

* Recommend that engines created with `ember addon my-engine` remove this setting from their `package.json` so that the default will be used.
* Recommend that engines created with `ember addon my-engine` always update this setting with the correct value (`config` by default).
* Use a different setting (other than `ember-addon/configPath`) to customize `configPath` for engines.
* Remove the option to provide a custom setting by reverting #133 until we have engine-specific blueprints.

Although we need to pick a path here, whatever we choose will become a non-issue once we introduce engine-specific blueprints so that engines can be generated with `ember engine my-engine`.

**Comment by cibernox** [comment]
@dgeb Is there any reason in particular preventing the implementation of the `ember engine my-engine` command in ember-cli?

**Comment by trentmwillis** [comment]
> Use a different setting (other than `ember-addon/configPath`) to customize `configPath` for engines.

I tend to favor this solution over the others. One thing that's not clear to me with the other solutions is how would you specify the dummy app's config path and the engine's config path in an addon? Since I am assuming you would need both in order to properly test things.

**Comment by dgeb** [comment]
@trentmwillis I hear you ... that makes sense to me. Although I have to say that the `configPath` pointing to the dummy app's config path feels a bit _off_ in the first place, but this is an established convention for all Ember addons. That's why I pinged @rwjblue for some perspective here.

@cibernox I hope to proceed with adding support for `ember engine my-engine` to ember-cli once we enable the engines flag by default in Ember (which will hopefully be quite soon).

**Comment by rwjblue** [comment]
> Although I have to say that the configPath pointing to the dummy app's config path feels a bit off in the first place, but this is an established convention for all Ember addons. That's why I pinged @rwjblue for some perspective here.

I agree with @dgeb on both accounts here.  The best path forward is likely `engine-config-path` (or `engineConfigPath`).

**Comment by cibernox** [comment]
@dgeb It's some kind of policy that a blueprint cannot be part of ember-cli until the experiment is stable? Maybe disclaimer that you're using an "experimental feature" could suffice.

**Comment by dgeb** [comment]
> The best path forward is likely engine-config-path (or engineConfigPath).

@rwjblue sounds good - I'll make that change soon and get out a new release.

**Comment by dgeb** [comment]
Fixed via https://github.com/dgeb/ember-engines/pull/152
