### ISSUE TITLE
Partial rollback of route-serializers RFC.

### ISSUE THREAD

**Issue by nathanhammond** [dgeb/ember-engines#156]
- [x] Merge the `ember-route-serializers` and `ember-application-engines` flags.
- [x] Remove the deprecation warnings on `Route#serialize()` for normal applications.
- [x] Throw an error when defining a route serializer not in an Engine's Route map.
- [x] Throw an error on custom `Route#serialize()` inside an Engine.

**Comment by trentmwillis** [comment]
There changes/fixes have been merged into core.
