### ISSUE TITLE
[0.2] Controller.transitionToRoute() doesn't work for engine routes

### ISSUE THREAD

**Issue by dnachev** [dgeb/ember-engines#159]
The problem is caused, because the `Controller.transitionToRoute()` relies on the `router.transitionTo()`, which is not patched to be engine aware.

**Comment by trentmwillis** [comment]
@dnachev any chance you could submit a fix for this? Seems like it should be straightforward.

**Comment by trentmwillis** [comment]
I've opened a PR to address this upstream: https://github.com/emberjs/ember.js/pull/14176

**Comment by dnachev** [comment]
Opened PR for v0.2 branch: https://github.com/dgeb/ember-engines/pull/188

**Comment by trentmwillis** [comment]
Closed via #188.
