### ISSUE TITLE
Link into engine from host app

### ISSUE THREAD

**Issue by mydea** [dgeb/ember-engines#161]
I am not sure if I just couldn't find it, or if this is not possible at the moment: I'd like to link from the host app into the engine, to a specific route, but that doesn't seem to work.

E.g.:

```js 
// app's router.js
this.route('blog', function() {
  this.mount('blog-engine', { path: '/' });
});
```

```js
// engine's routes.js
import buildRoutes from 'ember-engines/routes';

export default buildRoutes(function() {
  this.route('about');
});
```

This doesn't work in the host app:
```hbs
{{#link-to 'blog.about'}}About the blog{{/link-to}}
```

This would be extremely important for us. Is anything like this planned? Or is there a proposed solution for such a problem?

**Comment by dgeb** [comment]
Given the routes in your app, you would need to link-to `blog.blog-engine.about` instead of `blog.about`.

I'm guessing you actually want to redefine your routes as follows:

```
// app's router.js
this.mount('blog-engine', {as: 'blog'}); // note: no parent blog route
```

Given this change, you should be able to link-to `blog.about`.

**Comment by mydea** [comment]
Ah, perfect. I need to wrap it in another route, because there is a template there from the host app. Thank you!
