### ISSUE TITLE
Guard Engine config for SSR

### ISSUE THREAD

**Issue by trentmwillis** [dgeb/ember-engines#164]
With our SSR setup we're running into an issue where we error out when trying to read in an Engine's config due to attempting to use jQuery (https://github.com/dgeb/ember-engines/blob/master/lib/engine-config-from-meta.js#L7).

We have a hack in place for the app's `config/environment` but that isn't possible for the Engines. We would still like access to the config, but we're unsure of the best way around the DOM access. Any idea's how FastBoot handles this for the standard config?

cc/ @thousand @kratiahuja

**Comment by rwjblue** [comment]
Fastboot overrides the `app-name/config/environment` module to avoid the jQuery usage ([here](https://github.com/ember-fastboot/ember-cli-fastboot/pull/187)).

**Comment by kratiahuja** [comment]
Fastboot is doing the same way as we do with a little difference of providing an API as well. We probably need to unify our work with fastboot. 

For engines, we probably need a hook to do this kind of replacement.

**Comment by trentmwillis** [comment]
Okay, sounds like we want https://github.com/ember-cli/ember-cli/pull/5582 to land so that all the modules can flow through the same hook.

**Comment by trentmwillis** [comment]
@rwjblue what would you think about doing [something similar to this](https://github.com/null-null-null/ember-get-config/blob/master/index.js#L15-L19)? Where we just generate an actual module with the JSON stringified in it? I don't see a need to have the Engine's configuration inlined in the DOM, but I could be missing something.

**Comment by rwjblue** [comment]
Embedding the config into the asset means you cannot promote an asset from one environment to another.

**Comment by trentmwillis** [comment]
> Embedding the config into the asset means you cannot promote an asset from one environment to another.

@rwjblue can you explain this a bit more? Or perhaps provide an example of where it'd be bad? I read it like a dozen times but am still unsure what you mean.

**Comment by trentmwillis** [comment]
#175 was enough to allow us to work around the blocking issue. There likely needs to be a standard way of adding configs, but I don't think that discussion should be had in this repo, thus I am closing this issue.
