### ISSUE TITLE
Move query param fix upstream

### ISSUE THREAD

**Issue by dgeb** [dgeb/ember-engines#168]
The fix to share the bucket cache needs to be moved upstream to ember.

See https://github.com/dgeb/ember-engines/pull/166

As @rwjblue mentioned, the fix needs to go in here https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/engine-instance.js#L180-L183 along with tests.

**Comment by dnachev** [comment]
I will try to fix it upstream as well.

**Comment by dgeb** [comment]
Fixed via #170 - thanks @dnachev :shipit:
