### ISSUE TITLE
[0.2] Route.intermediateTransitionTo() doesn't prefix the routes

### ISSUE THREAD

**Issue by dnachev** [dgeb/ember-engines#186]
It needs to have the same prefixing done as the `transitionTo`.

**Comment by trentmwillis** [comment]
I think this will need to land upstream in Ember itself at this point. Likely [here](https://github.com/emberjs/ember.js/blob/3ec114528e349c08ed831719aed988f4e1a4616b/packages/ember-routing/lib/system/route.js#L2335-L2337). Though I think the issue still makes sense being here.

**Comment by trentmwillis** [comment]
I've opened a PR to address this upstream: https://github.com/emberjs/ember.js/pull/14176

**Comment by dnachev** [comment]
Opened PR for v0.2 branch: https://github.com/dgeb/ember-engines/pull/188

**Comment by nathanhammond** [comment]
I'm not sure that `intermediateTransitionTo` is a good API to support on the Engines side. (Or if it's a good public API at all, but that's beside the point.)

I _believe_ that this may bypass loading of engine assets if it tries to `intermediateTransitionTo` something that hasn't yet been loaded in. I also believe that it will fail from outside of an engine into a lazy engine.

**Comment by dnachev** [comment]
Good points. But if it is not deprecated and removed for applications as
well, I think it should be supported for transitions inside an engine.
Tempted to say out of an engine as well, but not passionate about it.

**Comment by dgeb** [comment]
Fixed via #188 and #207.
