### ISSUE TITLE
component can access route actions within engine

### ISSUE THREAD

**Issue by tyronepost** [dgeb/ember-engines#195]
I've discovered some unexpected behavior while refactoring a route into a set of sub components.  It seems that a component declared in a route's template can access the methods within route's action hash without the actions being passed down.

[Reproduction here](https://github.com/tyronepost/engineroutebug)

**Comment by nathanhammond** [comment]
That is expected behavior? String actions like that are bubbled up. See this example: https://ember-twiddle.com/4373f6e038d083cbbd88cbb5c91b9794?openFiles=routes.child.js%2C&route=%2Fchild

**Comment by tyronepost** [comment]
@nathanhammond Hmmm, ok.  I think I get what your saying, but I can't for the life of me figure out what is going on with the twiddle i put together before I opened the issue, which is almost identical to yours.

https://ember-twiddle.com/003e92fe42c100a67226955a8fa42a4a?openFiles=routes.my-route.js%2Ctemplates.components.my-component.hbs&route=%2Fmy-route

I get Uncaught Error: <Ember.Component:ember376> had no action handler for: hello

I was under the impression that route actions were somehow different from controller and component actions, and couldn't be referenced by subcomponents in the same manner without the assistance of an addon such as 

https://github.com/DockYard/ember-route-action-helper

I suppose I'll get there :P.  Maybe I'm equating string actions to closure actions, which I guess are different right?

**Comment by nathanhammond** [comment]
It's different in 2.7 and 2.8.

**Comment by nathanhammond** [comment]
See: emberjs/ember.js#14275

**Comment by rwjblue** [comment]
Ya, definitely an Ember bug.
