### ISSUE TITLE
[v0.3] - ember-metal/symbol has moved recently

### ISSUE THREAD

**Issue by mike-north** [dgeb/ember-engines#197]
The `symbol` module, [which ember-engines uses](https://github.com/dgeb/ember-engines/blob/v0.3/addon/routes.js#L3), seems to have been moved to a new `ember-utils` package. This is a breaking change (admittedly to totally private APIs) that prevents the `v0.3` branch from being used with ember 2.9-beta.x and newer releases. 

Fix for 2.9+ (to https://github.com/dgeb/ember-engines/blob/v0.3/addon/routes.js#L3). This will of course cause problems with older releases.
```js
const symbol = emberRequire('ember-utils/symbol');
```

**Comment by rwjblue** [comment]
Yeah, this was removed (in favor of simply using a brand on the object) in https://github.com/dgeb/ember-engines/pull/187.  We can do similar for the v3 branch.

**Comment by nathanhammond** [comment]
Will be addressed by #201. Closing this and tracking toward resolution there.
