### ISSUE TITLE
[QUESTION] Engines Addon vs Ember directly

### ISSUE THREAD

**Issue by eccegordo** [dgeb/ember-engines#199]
One thing that is not completely clear to me is will this addon always be required to use engines?
In other words is there an "out the box" experience for engines if I just install  Ember 2.8 or greater and nothing else?

The way I read the blog post on the ember site suggests that the addon is optional.

>The best way to use this feature in your apps is through the ember-engines addon.

Would it be possible to add a clarifying statement to this project's readme that outlines the essential differences of what is in Ember.js core vs in the Engines Addon.

Presumably the addon provides hooks, blueprints, and resolver tweaks that make the ember cli experience work well. But conversely it is theoretically possible to create engines just using the Ember.js core public engine apis.

**Comment by knownasilya** [comment]
I think you need to use this addon if you want engines to work, it's really the meat of the work.
The blog post probably stated it that way because the community might make alternate versions of engines using the hooks that Ember exposes. As far as I know, this is the only implementation at the moment.

**Comment by eccegordo** [comment]
@knownasilya OK, thanks. That is how I am interpreting it as well.

**Comment by nathanhammond** [comment]
Eventually this addon _may_ disappear and everything would Just Work™ out of the box with Ember and Ember CLI.

However, at present it isolates a lot of the incremental complexity of the solution from more stable portions of the Ember ecosystem. That is a tremendous feature and allows us to continue testing without fear of breaking things in existing applications.

I'm closing this, thanks for stopping by, let us know how things go in [#-ember-engines](https://embercommunity.slack.com/messages/-ember-engines/) on the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/)!
