### ISSUE TITLE
Routable in-repo-engine not working: "The route map for test-engine should be wrapped by 'buildRoutes' before exporting."

### ISSUE THREAD

**Issue by cqcsobreyra** [dgeb/ember-engines#204]
Console Says: "jquery.js:3793 Uncaught Error: Assertion Failed: The route map for test-engine should be wrapped by 'buildRoutes' before exporting."

I double checked the routes file is properly wrapped using buildRoutes:

```
//testapp/lib/test-engine/addon/routes.js

import buildRoutes from 'ember-engines/routes';

export default buildRoutes(function() {
    this.route('new');
});
```

To reproduce:
Using:
- ember-cli 2.8.0
- Ember 2.8.0
- ember-engines. 0.3.0

1.  ember new testapp
2.  ember install ember-engines
3.  ember g in-repo-engine test-engine
4.  ember serve
5.  Navigate to /test-engine
6.  View browser console

**Comment by trentmwillis** [comment]
@cqcsobreyra you likely need to update your `app/app.js` file to use the custom resolver provided by ember-engines: https://github.com/dgeb/ember-engines/tree/v0.3#customizing-the-resolver

**Comment by cqcsobreyra** [comment]
D'oh! Yep, skipped that step. Thank you.
