### ISSUE TITLE
buildRoutes wrapper not detected

### ISSUE THREAD

**Issue by taras** [dgeb/ember-engines#213]
I'm experimenting with refactoring HospitalRun into Ember Engines. I started with a Billing in-repo-engine. I moved all of the code and I'm getting the following error: `Uncaught Error: Assertion Failed: The route map for billing should be wrapped by 'buildRoutes' before exporting.`

[routes are wrapped in `buildRoutes`](https://github.com/HospitalRun/hospitalrun-frontend/blob/billing-engine/lib/billing/addon/routes.js) but that error still comes up.

Why is this happening?

**Comment by trentmwillis** [comment]
What version of ember-engines and ember-resolver are you using? We've made some changes to the internals recently so you likely just have a bad combination.

**Comment by dfalling** [comment]
I'm hitting this as well.  ember-resolver@2.1.0 and ember-engines@0.2.12 for my engine and my application.  Is there a recommended combination to use?

**Comment by trentmwillis** [comment]
If you are experiencing it while using version `0.2.12` then you likely are not importing the correct resolver. Make sure your application and the engine are both using the `ember-engines/resolver` import and not `ember-resolver`.

**Comment by dfalling** [comment]
Confirmed, that was it for me- I forgot to update my resolvers.  Thanks! (no guarantees this fixes @taras).

**Comment by nathanhammond** [comment]
Six days later with the fix for this message always being the resolver not included. Closing.
