### ISSUE TITLE
replaceWithExternal?

### ISSUE THREAD

**Issue by KevinJia191** [dgeb/ember-engines#230]
Hi, I have a use case in the ember-engine world where I would like to have one engine transition to another engine. However, the existing Route transition's replaceWith / transitionTo don't know how to transition to another engine (in the same app)

What is the best way to transition to another engine's route? I am currently using window.location.replace, but was hoping to use an ember transition

**Comment by knownasilya** [comment]
Maybe use a service from your parent app that could make the transition for you, e.g.

```js
crossEngine: inject.service(),
// ...
let crossEngine = this.get('crossEngine');
crossEngine.transition(engineName, route, args);
```

**Comment by KevinJia191** [comment]
I don't think thats a great permanent solution, but will definitely tide me over in the meantime

Thanks for the pointer!

**Comment by trentmwillis** [comment]
The sanctioned way of doing this is to use external routes, with the external aliased methods. The idea is that for when constructing links for things outside of your Engine you are saying "I want to link to `x`" and the application is then responsible for telling you where `x` is located at.

You can then, as your question title remarks, use `replaceWithExternal` (or `transitionToExternal`) to do the transition.

**Comment by trentmwillis** [comment]
Closing this as there is an established pattern with external routes now.
