### ISSUE TITLE
The `/routes.js` part in README is confusing

### ISSUE THREAD

**Issue by leizhao4** [dgeb/ember-engines#253]
It took me a while to figure out that it's actually `/addon/routes.js`, not `/routes.js`.

Also it would be great if README could include a link to the demo engine and the guides because they seem to be very helpful.

**Comment by trentmwillis** [comment]
Hey @leizhao4 would you mind opening a PR to fix these issues?

**Comment by leizhao4** [comment]
@trentmwillis Sure! Just opened #271.
