### ISSUE TITLE
RollupFunnel missing tests

### ISSUE THREAD

**Issue by stefanpenner** [dgeb/ember-engines#256]
https://github.com/dgeb/ember-engines/blob/master/lib/rollup-funnel.js

Examples of how to test broccoli plugins

* https://github.com/chadhietala/broccoli-rollup/blob/master/tests/index.js
* https://github.com/eploko/broccoli-watchify/blob/master/test/watchify-test.js
* https://github.com/broccolijs/broccoli-funnel/blob/master/tests/index.js

**Comment by trentmwillis** [comment]
I'm gonna work on this. Once the tests are in place we can work on #257 to ensure we avoid regressions.

**Comment by stefanpenner** [comment]
@trentmwillis awesome. Yes having tests will leave a nice foundation for future contributions (or bug fixers)

**Comment by trentmwillis** [comment]
Fixed and subsequently removed from this repo to a separate package.
