### ISSUE TITLE
[PERF] RollupFunnel is unstable

### ISSUE THREAD

**Issue by stefanpenner** [dgeb/ember-engines#257]
Although it is possible to implement naive broccoli-plugins, by merely rebuilding everything every time. This does not enable a performant build.

Typically an efficient plugin must:

* calculate a patchset: https://github.com/broccolijs/broccoli-funnel/blob/master/index.js#L304
* apply that patchset efficiently to a persistent output: https://github.com/broccolijs/broccoli-funnel/blob/master/index.js#L317-L319

---
In this case, it is likely sufficient to:

1. figure out what changed
2. apply changset to internal representation
3. apply additions/removals to satisfy the filter based on 2.

---

This does require some effort, some WIP existing [here](https://github.com/ember-cli/rfcs/pull/76) and [here](https://github.com/stefanpenner/fs-tree-diff/pull/36) to improve the ergonomics. Unfortunately, to implement on-trivial transforms efficiently requires extra care. On a plus side, it does enable power-users to get all the performance there hart desires.

It is unclear to my, why rollup is required here. As I believe the usage today is merely to extract deps, which can be done likely directly via some [ES parser](https://github.com/ef4/ember-browserify/blob/master/lib/stubs.js#L115-L135)

It is also not entirely clear, why folder structure + dependencies alone are not enough to infer the information. But there is maybe a featureset I am unaware of that supports this.

Anyways, A good place to get started would be to create a test ensure stable output, an example of such a test: https://github.com/eploko/broccoli-watchify/blob/master/test/watchify-test.js#L36-L62

**Comment by trentmwillis** [comment]
This should be fixed now.
