### ISSUE TITLE
Initializers and ember engines.  

### ISSUE THREAD

**Issue by kiwiupover** [dgeb/ember-engines#259]
In trying to make an in repo engine for travis-ci I ran into an issue where the auth service was not being passed through. 

I wonder if this initialzer is the issue. https://github.com/travis-ci/travis-web/blob/master/app/initializers/auth.js

I have pushed a branch here https://github.com/kiwiupover/travis-web/pull/1

addon/engine.js
```
...
const Eng = Engine.extend({
  modulePrefix,
  Resolver,
  dependencies: {
    services: [
      'auth'
    ]
  }
});
```

parent app.js
```
var App = Ember.Application.extend(Ember.Evented, {
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver,

  dependencies: {
    services: [
      'auth'
    ]
  },
...
``` 
Error `A dependency mapping for 'services.auth' must be declared on this engine's parent.`

**Comment by trentmwillis** [comment]
Your `app.js` has a malformed dependency map ([see documentation here](https://github.com/dgeb/ember-engines#providing-dependencies-to-engines)). It should look like:


```javascript
var App = Ember.Application.extend(Ember.Evented, {
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver: Resolver,

  engines: {
    engineName: {
      dependencies: {
        services: [
          'auth'
        ]
      }
    }
  },
...
```

**Comment by kiwiupover** [comment]
@thanks @trentmwillis totally right
