### ISSUE TITLE
Update Engines RFC to reflect developments in and lessons from this addon

### ISSUE THREAD

**Issue by dgeb** [dgeb/ember-engines#33]
- [x]  Document `{{mount}}` keyword
- [x]  Include `as` option for `mount` method to allow engine aliases
- [x] Should we allow arbitrary configuration attributes to be passed from the consuming application to the engine?
- [x] What is the long term future of this addon? Can it continue to exist by overriding only public methods?
- [x] Go further in depth into lazy loading issues (e.g. separation of route serializers)
- [ ] Should we remove the section about potential namespaced access to engines from parents? 
- [ ] Discuss synergies with routable components

**Comment by knownasilya** [comment]
That last point might be nice, but how is it any different than sharing a service?

**Comment by rwjblue** [comment]
Discussion from Ember F2F:

> Should we allow arbitrary configuration attributes to be passed from the consuming application to the engine?

Yes, the `{{mount}}` template keyword should allow normal handlebars style hash arguments.  The router DSL style should also allow some sort of API to supply parameters too, but the exact API is less obvious.

> What is the long term future of this addon? Can it continue to exist by overriding only public methods?

We decided that all overrides should be moved upstream into Ember itself, and that this addon will still continue to exist to provide blueprints/commands/etc as well as be the "single source" for importing `Engine`.

**Comment by dgeb** [comment]
Closing because the RFC has been merged and the remaining issues are now being tracked separately.
