### ISSUE TITLE
Could not find module `ember-resolver` imported from `ember-engines/resolver`

### ISSUE THREAD

**Issue by nucleartide** [dgeb/ember-engines#59]
Hey everyone, first of all this looks great! At work, I'm about to build an application as part of a larger application, and the "in-repo-addon" option seems really appropriate.

So I followed the readme and tried to create an in-repo-addon for a newly created Ember project, but once everything is fired up with `ember server` there seems to be an import error. I've pushed my code to a repo for reference: https://github.com/nucleartide/__ember-engines-test

<img width="1440" alt="screen shot 2016-01-29 at 12 06 26 pm" src="https://cloud.githubusercontent.com/assets/914228/12682376/10c0a460-c681-11e5-91bb-d3991adda8ba.png">

Am I doing something wrong?

**Comment by knownasilya** [comment]
Are you using ember canary?

**Comment by rwjblue** [comment]
This addon is expecting your app to be blueprinted with ember-cli@2.3.0-beta.1 or higher.  Looks like you ran `ember new foo` with 1.13.15.

**Comment by nucleartide** [comment]
@knownasilya @rwjblue Thanks for the prompt responses! I've updated to ember-cli@2.3.0-beta.1, but I get this stack trace now. The "blog" engine's code is here: https://github.com/nucleartide/__ember-engines-test/tree/master/lib/blog

```
Error: Assertion Failed: You attempted to mount the engine 'blog' in your router map, but the engine can not be found.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:47888:21)
    at assert (http://localhost:4200/assets/vendor.js:37616:13)
    at assert (http://localhost:4200/assets/vendor.js:47652:34)
    at _getEngineInstance (http://localhost:4200/assets/vendor.js:104191:9)
    at http://localhost:4200/assets/vendor.js:104224:34
    at Object.exports.default._routerUtils.subclass.applyToState (http://localhost:4200/assets/vendor.js:83732:23)
    at Object.getTransitionByIntent (http://localhost:4200/assets/vendor.js:82733:27)
    at Object.Router.transitionByIntent (http://localhost:4200/assets/vendor.js:82845:38)
    at doTransition (http://localhost:4200/assets/vendor.js:83417:19)

**Comment by dgeb** [comment]
@nucleartide I believe that your problem is that your in-repo blog engine does not contain an `addon` dir. You should move everything except your engine's `index.js` and `package.json` into that dir.

I've recently pushed a [demo app](https://github.com/dgeb/ember-engines-demo) that mounts both an in-repo route-less engine as well as a [standalone routable engine](https://github.com/dgeb/ember-blog-engine). You can compare these repos with yours if you have further problems.

**Comment by nucleartide** [comment]
Oh okay, thanks! Going to close this - I'll just refer to the demo app.
