### ISSUE TITLE
Missing template compiler

### ISSUE THREAD

**Issue by alecho** [dgeb/ember-engines#65]
When creating a new engine and I add a template for it i receive the following error: `Addon templates were detected, but there are no template compilers registered for...`.

**Comment by rwjblue** [comment]
You need to include `ember-cli-htmlbars` in your engines `package.json` under `dependencies` (which should be part of the rest of that message assuming it is [this one](https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L565-L569)).

**Comment by alecho** [comment]
Indeed it is. For some reason last night I didn't believe it. Is there a reason the add-on's generated package.json doesn't include it?

**Comment by trentmwillis** [comment]
@alecho I believe the reason for that is there is a sizable chance an addon won't introduce templates (could just be services or build tooling for example). I'll make sure it is included by default once I am able to finish work on the in-repo-engine blueprint/generator.

**Comment by trentmwillis** [comment]
Now that a release is out with the `in-repo-engine` blueprint this can probably be closed.
