### ISSUE TITLE
In apps with legacy view support enabled: TypeError: Attempting to register an unknown factory: `view:select`

### ISSUE THREAD

**Issue by JackieChiles** [dgeb/ember-engines#69]
When `Ember.ENV._ENABLE_LEGACY_VIEW_SUPPORT` is on, the following error occurs, preventing the app from loading:

<pre>
TypeError: Attempting to register an unknown factory: `view:select`
</pre>

**Comment by dgeb** [comment]
Fixed via #70 and published in v0.1.4
