### ISSUE TITLE
Can't resolve component from addon consumed by engine consumed by app

### ISSUE THREAD

**Issue by JackieChiles** [dgeb/ember-engines#74]
I have a basic engines test app here: https://github.com/JackieChiles/et-app. The app consumes an engine (https://github.com/JackieChiles/et-engine) which in turn consumes an addon (https://github.com/JackieChiles/et-addon) and uses `et-component` from that addon. The following work:

* Rendering `et-component` in `et-app`: https://github.com/JackieChiles/et-app/blob/master/app/templates/application.hbs#L6
* Rendering `et-component` in `et-engine`'s dummy app: https://github.com/JackieChiles/et-engine/blob/master/tests/dummy/app/templates/application.hbs#L1
* Rendering `et-en-component` (lives in `et-engine` directly) in `et-app` through a template in the engine: https://github.com/JackieChiles/et-engine/blob/master/addon/templates/et-template.hbs#L5

But I haven't been able to get `et-component` to render in `et-app` though a template in the engine at all: https://github.com/JackieChiles/et-engine/blob/master/addon/templates/et-template.hbs#L2

I do see `et-addon/components/et-component/component` and `et-app/components/et-component/component` in the resolver's module names list when Ember tries to render that component, but it's looking for `et-engine/components/et-component/component`.

Is there a piece that I'm missing or is this a possible bug/gap?

**Comment by timkendall** [comment]
Yeah I'm having the same issue :\ Seems like we should be able to just do something like:

```js
export default Engine.extend({
  modulePrefix: 'registration-engine',
  Resolver,

  dependencies: {
    services: [ 'store' ],
    components: [ 'transition-group', 'one-way-controls', 'some-other-component' ]
  }
});

```

**Comment by mike183** [comment]
@timkendall such functionality is currently being discussed in #58

**Comment by rwjblue** [comment]
https://github.com/JackieChiles/et-engine/blob/master/package.json#L40 is incorrect, if your engine depends on a given external addon it must be listed in `dependencies` (not `devDependencies`).

I proposed https://github.com/JackieChiles/et-engine/pull/1 to show what I mean.

**Comment by timkendall** [comment]
@JackieChiles  Also make sure that you modified your `index.js` in the root of your project like it says in the README. That was something I missed lol

**Comment by rwjblue** [comment]
I think that PR + wrapping index.js (which I believe `et-engine` was doing) should resolve this.  I'm going to close, but am happy to reopen if that doesn't fix...

**Comment by JackieChiles** [comment]
@rwjblue That PR fixed the issue, thanks! I could have sworn I tried that at some point before, but it seems not.

**Comment by JackieChiles** [comment]
@timkendall Currently of course only services are supported as engine dependencies, but as already mentioned I believe injecting other types is being discussed. But, the PR that fixed the issue for me makes sense: making the engine's addons `dependencies` instead of `devDependencies` allows them to propagate down to whatever app consumes the engine. Hope this thread helped you!
