### ISSUE TITLE
Documentation shortcomings

### ISSUE THREAD

**Issue by vlascik** [dgeb/ember-engines#78]
So I tried to turn my apps into engines, and I kept struggling with the lack of documentation on several issues:
- feature flag needed for canary and engines is not mentioned
- it is not immediately clear that the path to routes.js should be addon/routes.js, had to look into the dummy app
- the fact that in engine htmlbars should be in dependencies instead of devDependencies is not mentioned. what is going on wrt dependencies/devDependencies in not exactly clear, where should the engine's dependencies go?
- does engine have its own application route/template/adapters etc, or does it use the ones from parent app?
- I keep getting "Assertion Failed: A helper named 'title' could not be found" on all helpers coming from addons, even though they work in parent application, and they are also included in engine. 
- if I include addons in parent app, should I also put them in an engine if I need them, will it load twice if I go to the engine, or is the deduplication as mentioned in RFC working yet?
- does the resolver support namespace lookups as described in RFC? If so, couple of examples in readme would be nice
- where to put the configuration, how is it merged, which file takes precedence in case of conflict?
- some best practices would be helpful, e.g. what to put into app/ and what to put into addon/ folders (where to put templates, services, etc), maybe some instructions on how to turn an existing app into engine, couple of lines on what are the key differences between apps, addons and engines, or a bit more complex tutorial? 

There is pretty much no documentation on engines except for readme and RFC. Maybe it's just because I'm not an Ember expert yet (haven't written any addon, are they mostly the same thing?), but even small questions like this quickly add up to hours of searching and debugging, hm.

**Comment by knownasilya** [comment]
One thing to keep in mind, is that this is still alpha software (requires using ember canary) so documentation isn't the primary concern yet since the APIs are still changing quite a bit. I'm sure the developers would appreciate any small additions you can make, but things will change fast, so the docs will need to be revised.

**Comment by vlascik** [comment]
I wish I could contribute more answers, but I wasn't able to make it work (primarily because of the helper error). At least I tried to write down what tripped me up, I suspect it will be similar for most newcomers to engines, I realized these newbie issues might be hard to imagine for someone knowing all the implementation details already.
Anyway, my questions are more conceptual and do not concern APIs that much. I think the more people will be able to test it out, the sooner the issues will be ironed out and engines can start being considered stable enough. 
But that requires some sort of usable documentation. The code probably is almost there already, we just need to be able to use it.

**Comment by dgeb** [comment]
@vlascik I'm sorry you had trouble getting up and running and appreciate you taking the time to document why. As @knownasilya mentioned, this addon is still alpha, but we hope to stabilize it and improve the documentation soon. I'll step through your questions soon and fill out the answers either here or in the readme (or both). For now, a good resource is this [demo app](https://github.com/dgeb/ember-engines-demo) and [demo engine](https://github.com/dgeb/ember-blog-engine).

**Comment by dgeb** [comment]
Big thanks to @trentmwillis for putting together some in-repo [guides](https://github.com/dgeb/ember-engines/blob/master/guides/01-introduction.md). 🎉 

Please open specific issues or PRs to address any remaining documentation shortcomings.
