### ISSUE TITLE
Dozens of DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge] warnings

### ISSUE THREAD

**Issue by vlascik** [dgeb/ember-engines#79]
With current canary,  engines throw dozens of ```DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge]``` warnings.

**Comment by trentmwillis** [comment]
This can be closed now, was fixed in #84.
