### ISSUE TITLE
Component fails to re-render when used with bound value in Engine

### ISSUE THREAD

**Issue by trentmwillis** [dgeb/ember-engines#85]
**Issue:** When using a component in an Engine (either routeless or routable as far as I can tell) with a bound value, if you try to re-render it by modifying the bound value, the re-render will fail with an error like:

```bash
Uncaught Error: Assertion Failed: A helper named '<component-name>' could not be found
```

**Potential Cause:** After a good amount of digging, it appears that when the re-render occurs the lookups are done in the context of the consuming application and not the engine. Thus, this error makes sense as the component won't be found and the application will fall back to trying to lookup a helper of the same name (which will also not be found).

Obviously, this is not the intended behavior and the re-render of a component should occur in the same context as the original render. However, my knowledge of the rendering internals in Ember is not very good, so I didn't make much progress on any actual solution.

**Repro:** I've put together a simple reproduction of the issue on the [`re-render` branch of my fork](https://github.com/trentmwillis/ember-engines/tree/re-render). If you start that up and visit the `routable-engine-demo/blog` route, the error will occur.

cc @nathanhammond @rileyhilliard

**Comment by dgeb** [comment]
Thanks for reporting, @trentmwillis. I'll investigate.
