### ISSUE TITLE
best practice for app repo setup with engines?

### ISSUE THREAD

**Issue by donahchoo** [dgeb/ember-engines#93]
hi,

is there a recommended best practice for setting an app that is going to use ember engines?  We want to have multiple applications and use engines to tie them together, but we don't know if we should have a single repo or multiple repos.  I think we would prefer a single repo because it can be easier to deal with.

thx!

**Comment by jbailey4** [comment]
We are doing some work at my company with engines and the best practice IMO is definitely separate repos. You want the installation of your addons/engines to be simple.

**Comment by knownasilya** [comment]
You could use in-repo-engines, really depends on your companies setup.

**Comment by donahchoo** [comment]
thanks!
