### ISSUE TITLE
Depends on unpublished ember-chat package

### ISSUE THREAD

**Issue by ef4** [dgeb/ember-engines#94]
Looks like a devDependency on ember-chat may have been added by mistake.

**Comment by trentmwillis** [comment]
That's one of the [dummy engines](https://github.com/dgeb/ember-engines/tree/master/tests/dummy/lib) used to test the addon. You need to run [`npm run-script prepublish`](https://github.com/dgeb/ember-engines/blob/master/package.json#L13) before attempting to develop in the repo; it symlinks the dummy engines so they behave like normal addons instead of in-repo-addons (should probably document that somewhere).

**Comment by ef4** [comment]
I submitted the above PR and then came back here and read more carefully:

> so they behave like normal addons instead of in-repo-addons

Is there really a relevant difference in behavior? What is it?

**Comment by trentmwillis** [comment]
Not entirely sure, I'll leave that up to @dgeb to answer.

**Comment by rwjblue** [comment]
Running `npm install` in the repo, should also run the `prepublish` script automatically.

I commented in #95 about why we have the current setup. Basically, in-repo-addons are considered `dependencies` by ember-cli, not `devDependencies`.  This means that if we published with the changes in #95 (which is how we initially started development) we would have to ship these test addons bundled in the `ember-engines` package **AND** they would be included by all consumers. 😿

**Comment by trentmwillis** [comment]
> Running npm install in the repo, should also run the prepublish script automatically.

Unfortunately `prepublish` runs _after_ you have installed dependencies. That way anything that needs dependencies (e.g., compiling code) can use the installed dependencies.

**Comment by rwjblue** [comment]
Ugh. OK.  So we just need to make it easier to dev in the repo.  I'm not sure of the best approach...

**Comment by trentmwillis** [comment]
Looks like we could specify the path: https://docs.npmjs.com/files/package.json#local-paths

**Comment by ef4** [comment]
We could fail early with a friendly error message.

**Comment by dgeb** [comment]
I'll explore some options. This has been an annoyance for a while.

**Comment by trentmwillis** [comment]
@dgeb think I have a solution.

**Comment by dgeb** [comment]
Closed via #97
